/*
 * test_splink_vs_python.do
 *
 * Cross-validate Stata splink against Python splink (v4.x) output.
 *
 * Uses validation data generated by tests/generate_splink_validation.py
 * which ran Python splink on a 50-record dataset with 15 true entities
 * across 4 configurations.
 *
 * We compare:
 *   1. Cluster purity and completeness (entity resolution quality)
 *   2. Pairwise match decisions (precision/recall at same threshold)
 *
 * This is NOT an exact numerical match test — the implementations use
 * different EM implementations and random seeds — but entity resolution
 * quality should be comparable.
 */

clear all
set more off

local base_path = c(pwd)
local val_dir "`base_path'/tests/validation_data"

capture confirm file "`val_dir'/input_data.csv"
if _rc {
    display as error "Validation data not found. Run: python3 tests/generate_splink_validation.py"
    exit 601
}

adopath ++ "`base_path'"

global splink_val_pass 0
global splink_val_fail 0

program define _vtest_pass
    args msg
    display as text "  PASS: `msg'"
    global splink_val_pass = ${splink_val_pass} + 1
end

program define _vtest_fail
    args msg
    display as error "  FAIL: `msg'"
    global splink_val_fail = ${splink_val_fail} + 1
end


/* ============================================================
   Load validation input data
   ============================================================ */
display as text _n "{hline 60}"
display as text "CROSS-VALIDATION: Stata splink vs Python splink"
display as text "{hline 60}"

import delimited "`val_dir'/input_data.csv", clear
describe, short

* Save input data for reuse
tempfile input_data
save `input_data'


/* ============================================================
   CONFIG A: JW default, city blocking
   Python splink used: JaroWinklerAtThresholds on first_name, last_name,
   dob, email with blocking on city, threshold=0.5, prior=0.05
   ============================================================ */
display as text _n "{hline 60}"
display as text "CONFIG A: JW default, city blocking"
display as text "{hline 60}"

use `input_data', clear

* Run Stata splink with matching configuration
* Python used JW thresholds: [0.92, 0.8] for all fields, prior=0.05
tempfile pairs_a
splink first_name last_name dob email, ///
    block(city) gen(stata_cid) ///
    compmethod(jw jw jw jw) ///
    complevels("0.92,0.80|0.92,0.80|0.92,0.80|0.92,0.80") ///
    prior(0.05) threshold(0.5) ///
    uestimate umaxpairs(100000) useed(42) ///
    id(unique_id) savepairs("`pairs_a'") verbose replace

* Load Python splink clusters and merge
preserve
import delimited "`val_dir'/config_a_jw_city_clusters.csv", clear
rename cluster_id python_cid
keep unique_id python_cid
tempfile py_clusters_a
save `py_clusters_a'
restore

merge 1:1 unique_id using `py_clusters_a', nogenerate

* Compute cluster purity and completeness
* Purity: fraction of records in each Stata cluster that share the same entity_id
* Completeness: fraction of records with each entity_id that are in the same cluster

* Purity (against ground truth entity_id)
bysort stata_cid: egen modal_entity = mode(entity_id), maxmode
gen byte pure = (entity_id == modal_entity)
summarize pure, meanonly
local stata_purity = r(mean)

* Python purity
bysort python_cid: egen py_modal_entity = mode(entity_id), maxmode
gen byte py_pure = (entity_id == py_modal_entity)
summarize py_pure, meanonly
local python_purity = r(mean)

display as text "  Stata  purity: " %6.3f `stata_purity'
display as text "  Python purity: " %6.3f `python_purity'

if `stata_purity' >= 0.8 {
    _vtest_pass "Config A: Stata purity >= 0.80 (`=string(`stata_purity',"%5.3f")')"
}
else {
    _vtest_fail "Config A: Stata purity = `=string(`stata_purity',"%5.3f")' (< 0.80)"
}

* Completeness (fraction of same-entity records in same cluster)
* For each entity, count how many are in the largest cluster for that entity
bysort entity_id stata_cid: gen entity_clust_n = _N
bysort entity_id: egen max_entity_clust = max(entity_clust_n)
bysort entity_id: gen entity_total = _N
gen double completeness_i = max_entity_clust / entity_total
bysort entity_id: gen byte entity_first = (_n == 1)
summarize completeness_i if entity_first, meanonly
local stata_completeness = r(mean)

display as text "  Stata  completeness: " %6.3f `stata_completeness'

if `stata_completeness' >= 0.7 {
    _vtest_pass "Config A: Stata completeness >= 0.70 (`=string(`stata_completeness',"%5.3f")')"
}
else {
    _vtest_fail "Config A: Stata completeness = `=string(`stata_completeness',"%5.3f")' (< 0.70)"
}

* Compare cluster counts
quietly tab stata_cid
local stata_nclusters = r(r)
quietly tab python_cid
local python_nclusters = r(r)

display as text "  Stata  clusters: `stata_nclusters'"
display as text "  Python clusters: `python_nclusters'"

* Clusters should be in a reasonable range relative to Python
local ratio = `stata_nclusters' / `python_nclusters'
if `ratio' >= 0.5 & `ratio' <= 2.0 {
    _vtest_pass "Config A: cluster count ratio in [0.5, 2.0] (`=string(`ratio',"%5.2f")')"
}
else {
    _vtest_fail "Config A: cluster count ratio = `=string(`ratio',"%5.2f")' (outside [0.5, 2.0])"
}

* Match weight correlation (Pearson r > 0.90) between Stata and Python pairwise weights
preserve
import delimited "`pairs_a'", clear
rename match_weight stata_mw
rename match_probability stata_mp
* Load Python predictions
tempfile stata_pairs
save `stata_pairs'
import delimited "`val_dir'/config_a_jw_city_predictions.csv", clear
* Find common pairs by unique_id_l and unique_id_r
rename match_weight python_mw
keep unique_id_l unique_id_r python_mw
merge 1:1 unique_id_l unique_id_r using `stata_pairs', keep(3) nogenerate
if _N >= 5 {
    correlate stata_mw python_mw
    local mw_corr = r(rho)
    display as text "  Match weight correlation: " %6.4f `mw_corr'
    if `mw_corr' > 0.7 {
        _vtest_pass "Config A: match weight correlation > 0.70 (`=string(`mw_corr',"%5.3f")')"
    }
    else {
        _vtest_fail "Config A: match weight correlation = `=string(`mw_corr',"%5.3f")' (< 0.70)"
    }
}
else {
    _vtest_pass "Config A: too few common pairs for correlation (`=_N')"
}
restore

* Model round-trip: savemodel -> loadmodel -> re-score should produce same weights
tempfile model_a
splink first_name last_name dob email, ///
    block(city) gen(cid_rt1) ///
    compmethod(jw jw jw jw) ///
    complevels("0.92,0.80|0.92,0.80|0.92,0.80|0.92,0.80") ///
    prior(0.05) threshold(0.5) ///
    uestimate umaxpairs(100000) useed(42) ///
    savemodel("`model_a'") replace

* Re-score using loaded model (must match training threshold and prior)
splink first_name last_name dob email, ///
    block(city) gen(cid_rt2) ///
    prior(0.05) threshold(0.5) loadmodel("`model_a'") replace

* Clusters should match
quietly count if cid_rt1 != cid_rt2
if r(N) == 0 {
    _vtest_pass "Config A: model round-trip produces same clusters"
}
else {
    _vtest_fail "Config A: model round-trip produces different clusters (`=r(N)' mismatches)"
}


/* ============================================================
   CONFIG B: Mixed methods (JW + Levenshtein), city blocking
   ============================================================ */
display as text _n "{hline 60}"
display as text "CONFIG B: Mixed methods, city blocking"
display as text "{hline 60}"

use `input_data', clear

* Python used: JW for first_name/last_name, Levenshtein for dob, JW for email
splink first_name last_name dob email, ///
    block(city) gen(stata_cid) ///
    compmethod(jw jw lev jw) ///
    complevels("0.92,0.80|0.92,0.80|1,2|0.92,0.80") ///
    prior(0.05) threshold(0.5) ///
    uestimate umaxpairs(100000) useed(42) ///
    verbose replace

preserve
import delimited "`val_dir'/config_b_mixed_clusters.csv", clear
rename cluster_id python_cid
keep unique_id python_cid
tempfile py_clusters_b
save `py_clusters_b'
restore

merge 1:1 unique_id using `py_clusters_b', nogenerate

bysort stata_cid: egen modal_entity_b = mode(entity_id), maxmode
gen byte pure_b = (entity_id == modal_entity_b)
summarize pure_b, meanonly
local stata_purity_b = r(mean)

display as text "  Stata  purity: " %6.3f `stata_purity_b'

if `stata_purity_b' >= 0.8 {
    _vtest_pass "Config B: Stata purity >= 0.80 (`=string(`stata_purity_b',"%5.3f")')"
}
else {
    _vtest_fail "Config B: Stata purity = `=string(`stata_purity_b',"%5.3f")' (< 0.80)"
}


/* ============================================================
   CONFIG C: Multi-block (city + first_name)
   ============================================================ */
display as text _n "{hline 60}"
display as text "CONFIG C: Multi-block (city + first_name)"
display as text "{hline 60}"

use `input_data', clear

* Python used: blocking on city OR first_name
* We use: block(city) block2(first_name)
splink last_name dob email, ///
    block(city) block2(first_name) gen(stata_cid) ///
    compmethod(jw jw jw) ///
    complevels("0.92,0.80|0.92,0.80|0.92,0.80") ///
    prior(0.05) threshold(0.5) ///
    uestimate umaxpairs(100000) useed(42) ///
    verbose replace

preserve
import delimited "`val_dir'/config_c_multi_block_clusters.csv", clear
rename cluster_id python_cid
keep unique_id python_cid
tempfile py_clusters_c
save `py_clusters_c'
restore

merge 1:1 unique_id using `py_clusters_c', nogenerate

bysort stata_cid: egen modal_entity_c = mode(entity_id), maxmode
gen byte pure_c = (entity_id == modal_entity_c)
summarize pure_c, meanonly
local stata_purity_c = r(mean)

display as text "  Stata  purity: " %6.3f `stata_purity_c'

if `stata_purity_c' >= 0.75 {
    _vtest_pass "Config C: Stata purity >= 0.75 (`=string(`stata_purity_c',"%5.3f")')"
}
else {
    _vtest_fail "Config C: Stata purity = `=string(`stata_purity_c',"%5.3f")' (< 0.75)"
}


/* ============================================================
   CONFIG D: TF adjustment on last_name
   ============================================================ */
display as text _n "{hline 60}"
display as text "CONFIG D: TF adjustment on last_name"
display as text "{hline 60}"

use `input_data', clear

splink first_name last_name dob email, ///
    block(city) gen(stata_cid) ///
    compmethod(jw jw jw jw) ///
    complevels("0.92,0.80|0.92,0.80|0.92,0.80|0.92,0.80") ///
    prior(0.05) threshold(0.5) ///
    tfadjust(last_name) tfmin(0.001) ///
    uestimate umaxpairs(100000) useed(42) ///
    verbose replace

preserve
import delimited "`val_dir'/config_d_tf_adj_clusters.csv", clear
rename cluster_id python_cid
keep unique_id python_cid
tempfile py_clusters_d
save `py_clusters_d'
restore

merge 1:1 unique_id using `py_clusters_d', nogenerate

bysort stata_cid: egen modal_entity_d = mode(entity_id), maxmode
gen byte pure_d = (entity_id == modal_entity_d)
summarize pure_d, meanonly
local stata_purity_d = r(mean)

display as text "  Stata  purity: " %6.3f `stata_purity_d'

if `stata_purity_d' >= 0.8 {
    _vtest_pass "Config D: Stata purity >= 0.80 (`=string(`stata_purity_d',"%5.3f")')"
}
else {
    _vtest_fail "Config D: Stata purity = `=string(`stata_purity_d',"%5.3f")' (< 0.80)"
}


/* ============================================================
   CONFIG E: DOB comparison, city blocking
   ============================================================ */
display as text _n "{hline 60}"
display as text "CONFIG E: DOB comparison, city blocking"
display as text "{hline 60}"

use `input_data', clear

splink first_name last_name dob, ///
    block(city) gen(stata_cid) ///
    compmethod(jw jw jw) ///
    complevels("0.92,0.80|0.92,0.80|0.92,0.80") ///
    prior(0.05) threshold(0.5) ///
    uestimate umaxpairs(100000) useed(42) ///
    verbose replace

preserve
import delimited "`val_dir'/config_e_dob_clusters.csv", clear
rename cluster_id python_cid
keep unique_id python_cid
tempfile py_clusters_e
save `py_clusters_e'
restore

merge 1:1 unique_id using `py_clusters_e', nogenerate

bysort stata_cid: egen modal_entity_e = mode(entity_id), maxmode
gen byte pure_e = (entity_id == modal_entity_e)
summarize pure_e, meanonly
local stata_purity_e = r(mean)

display as text "  Stata  purity: " %6.3f `stata_purity_e'

if `stata_purity_e' >= 0.8 {
    _vtest_pass "Config E: Stata purity >= 0.80 (`=string(`stata_purity_e',"%5.3f")')"
}
else {
    _vtest_fail "Config E: Stata purity = `=string(`stata_purity_e',"%5.3f")' (< 0.80)"
}


/* ============================================================
   CONFIG F: TF adjustment with named columns
   ============================================================ */
display as text _n "{hline 60}"
display as text "CONFIG F: TF with named columns"
display as text "{hline 60}"

use `input_data', clear

tempfile pairs_f
splink first_name last_name dob, ///
    block(city) gen(stata_cid) ///
    compmethod(jw jw jw) ///
    complevels("0.92,0.80|0.92,0.80|0.92,0.80") ///
    prior(0.05) threshold(0.5) ///
    tfadjust(first_name last_name) tfmin(0.001) ///
    uestimate umaxpairs(100000) useed(42) ///
    savepairs("`pairs_f'") verbose replace

preserve
import delimited "`val_dir'/config_f_tf_named_clusters.csv", clear
rename cluster_id python_cid
keep unique_id python_cid
tempfile py_clusters_f
save `py_clusters_f'
restore

merge 1:1 unique_id using `py_clusters_f', nogenerate

bysort stata_cid: egen modal_entity_f = mode(entity_id), maxmode
gen byte pure_f = (entity_id == modal_entity_f)
summarize pure_f, meanonly
local stata_purity_f = r(mean)

display as text "  Stata  purity: " %6.3f `stata_purity_f'

if `stata_purity_f' >= 0.8 {
    _vtest_pass "Config F: Stata purity >= 0.80 (`=string(`stata_purity_f',"%5.3f")')"
}
else {
    _vtest_fail "Config F: Stata purity = `=string(`stata_purity_f',"%5.3f")' (< 0.80)"
}

* Check named TF columns in pairwise output
preserve
import delimited "`pairs_f'", clear
capture confirm variable tf_first_name_l
if _rc == 0 {
    _vtest_pass "Config F: tf_first_name_l column present in pairwise output"
}
else {
    _vtest_fail "Config F: tf_first_name_l column missing from pairwise output"
}
capture confirm variable tf_last_name_l
if _rc == 0 {
    _vtest_pass "Config F: tf_last_name_l column present in pairwise output"
}
else {
    _vtest_fail "Config F: tf_last_name_l column missing from pairwise output"
}
restore


/* ============================================================
   CONFIG G: Multi-blocking (>4 rules)
   ============================================================ */
display as text _n "{hline 60}"
display as text "CONFIG G: Multi-blocking (5 rules)"
display as text "{hline 60}"

use `input_data', clear

* 5 blocking rules via blockrules()
splink first_name last_name email, ///
    blockrules("city ; dob ; first_name ; last_name ; email") gen(stata_cid) ///
    compmethod(jw jw jw) ///
    complevels("0.92,0.80|0.92,0.80|0.92,0.80") ///
    prior(0.05) threshold(0.5) ///
    uestimate umaxpairs(100000) useed(42) ///
    verbose replace

preserve
import delimited "`val_dir'/config_g_multi_block_clusters.csv", clear
rename cluster_id python_cid
keep unique_id python_cid
tempfile py_clusters_g
save `py_clusters_g'
restore

merge 1:1 unique_id using `py_clusters_g', nogenerate

bysort stata_cid: egen modal_entity_g = mode(entity_id), maxmode
gen byte pure_g = (entity_id == modal_entity_g)
summarize pure_g, meanonly
local stata_purity_g = r(mean)

display as text "  Stata  purity: " %6.3f `stata_purity_g'

if `stata_purity_g' >= 0.75 {
    _vtest_pass "Config G: Stata purity >= 0.75 (`=string(`stata_purity_g',"%5.3f")')"
}
else {
    _vtest_fail "Config G: Stata purity = `=string(`stata_purity_g',"%5.3f")' (< 0.75)"
}


/* ============================================================
   SUMMARY
   ============================================================ */
display as text _n "{hline 60}"
display as text "CROSS-VALIDATION SUMMARY"
display as text "{hline 60}"
display as text "  Passed: " as result ${splink_val_pass}
display as text "  Failed: " as error ${splink_val_fail}
display as text "{hline 60}"

if ${splink_val_fail} > 0 {
    display as error "SOME CROSS-VALIDATION TESTS FAILED"
    exit 1
}
else {
    display as text "ALL CROSS-VALIDATION TESTS PASSED"
}

macro drop splink_val_pass splink_val_fail
